### ISSUE TITLE
entrypoint.sh assumes public github.com server

### ISSUE THREAD

**Issue by kasuteru** [Azure/appservice-build#37]
The current entrypoint.sh file assumes that the repository is hosted on github.com and throws an error when run from Github Enterprise server:

https://github.com/Azure/appservice-build/blob/9ec371c908167a7a898a9d53ae6cc6bf8286092f/entrypoint.sh#L70

`https://api.github.com` needs to be replaced with `${GITHUB_API_URL}` as documented [here](https://docs.github.com/en/actions/reference/environment-variables#default-environment-variables). I will send a PR for this.

**Comment by cormacpayne** [comment]
@kasuteru Hey Thomas -- apologies for the _long_ delay, but I just merged your PR and it will be a part of a new version release of this GitHub Action. Thanks for the fix!
